name: Deploy
permissions:
  contents: write
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: sveltekit-build
          path: |
            build/
            !build/**/*.map    # excludes source maps
          retention-days: 7 # how long to keep the artifact

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev

    steps:
      - name: Deploy to Dev
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

  tag_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"
          git tag -a $TAG_NAME -m "Automated tag: $TAG_NAME"
          git push origin $TAG_NAME

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod"
