name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Build
        run: |
          echo "Running build"
  db-migration-push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Push to DB
        run: |
          echo "Pushing migrations to DB"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: db-migration-push
    environment: dev

    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev"

  tag_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"
          git tag -a $TAG_NAME -m "Automated tag: $TAG_NAME"
          git push origin $TAG_NAME

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod"
