name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Build
        run: |
          echo "Running build"
  db-migration-push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Push to DB
        run: |
          echo "Pushing migrations to DB"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: db-migration-push
    environment: dev

    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev"

  tag:
    runs-on: ubuntu-latest
    needs: deploy-dev

    steps:
      - name: Tag
        run: |
          echo "Tagging"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod

    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod"
