name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Build
        run: |
          echo "Running build"
  db-migration-push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Push to DB
        run: |
          echo "Pushing migrations to DB"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: db-push

    steps:
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev"

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-dev

    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging

    steps:
      - name: Deploy to Prod
        run: |
          echo "Deploying to Prod"
